### PR TITLE
AsyncEventBus: fix multiple listeners

### LINKED ISSUE #270: AsyncEventBus subscribing two callbacks for the same event results in only one being called twice
* Nim Compiler Version 1.6.4
* chronos-3.0.11 (installed via nimble)

``` nim
import chronos

type
  Payload = object
    test: int

let eventBus = newAsyncEventBus()

proc eventEV1(bus: AsyncEventBus, payload: EventPayload[Payload]) {.async.} =
  echo "eventEV1"

proc eventEV2(bus: AsyncEventBus, payload: EventPayload[Payload]) {.async.} =
  echo "eventEV2"

proc main() {.async.} =
  var payload: Payload
  discard eventBus.subscribe("EV", eventEV1)
  discard eventBus.subscribe("EV", eventEV2)
  eventBus.emit("EV", payload)
  await sleepAsync(1000)

waitFor main()
```

Expected output:
```
eventEV1
eventEV2
```

Actual output:
```
eventEV2
eventEV2
```

### PR DESCRIPTION
**Pull request by Menduist**
closes #270

### CODE REVIEW

File: chronos/asyncsync.nim [hunk 1]
```diff
@@ -561,6 +561,13 @@ proc emit[T](bus: AsyncEventBus, event: string, data: T, loc: ptr SrcLoc) =
         var data = EventPayload[T](value: data, loc: loc)
         cast[EventPayloadBase](data)
 
+  # Used to capture the "subscriber" variable in the loops
+  # suger.capture doesn't work in Nim <1.6
```
Comment (dbrignoli) [inline chronos/asyncsync.nim:565]: typo: ~suger~ -> sugar

**Comment by dbrignoli** [comment]
Hi @Menduist , is something holding back this fix from being merged? Thank you!

File: chronos/asyncsync.nim (hunk 1 above)
Comment (Menduist) [reply chronos/asyncsync.nim:565]:
```suggestion
  # sugar.capture doesn't work in Nim <1.6
```
